<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ProxySerializationSurrogate.cs" />
    <Compile Remove="NtlmHttp\Ntlm.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
  </ItemGroup>

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>Microsoft.Xrm.Sdk</PackageId>
    <Authors>Microsoft.Xrm.Sdk</Authors>
    <PackageReleaseNotes></PackageReleaseNotes>
    <RepositoryUrl></RepositoryUrl>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
